### PR TITLE
we removed the brainrot

### PR DESCRIPTION
**Pull request by WGrav01**
thanks bobler for your help, couldn't have done it without you

### CODE REVIEW

**Review by WGrav02 — APPROVED** [review]
i hope this one gets merged now, dang

**Review by WGrav03 — APPROVED** [review]
good job @Bobler6, i know its tough but you finally cured yourself

**Review by Kanao42 — APPROVED** [review]

**Comment by Bobler6** [comment]
no

**Comment by WGrav01** [comment]
yes

**Pull request closed without merging**
