### PR TITLE
removed brainrot

### PR DESCRIPTION
**Pull request by WGrav01**

### CODE REVIEW

**Review by WGrav02 — APPROVED** [review]
lgtm

**Review by WGrav03 — APPROVED** [review]
yep, code looks clean & good, approved

**Review by Irishman702 — COMMENTED** [review]
Very good, brain rot is gone

**Review by Irishman702 — APPROVED** [review]
Good

**Review by WGrav03 — APPROVED** [review]
still looks good to me

**Review by WGrav02 — APPROVED** [review]
same here

**Review by Irishman702 — APPROVED** [review]

**Review by Kanao42 — APPROVED** [review]

**Comment by WGrav02** [comment]
what

**Comment by WGrav01** [comment]
hang on let me open a new pr

**Comment by WGrav02** [comment]
ok

**Pull request closed without merging**
